name: Lint

on:
  push:
    branches:
      - '**' # all branches
  pull_request:
    branches:
      - '**' # all branches

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
